export const productData = [
  {
    id: 1,
    discount: "Sale 15%",
    image: [
      "/public/assets/coffemachine.jpg",
      "/public/assets/iphone.jpg",
      "/public/assets/microwave.jpg",
    ],
    make: "SMEG",
    starRating: 5.0,
    reviews: 5398,
    price: 985.99,
    oldPrice: 1056.0,
    description: "High-quality coffee machine with advanced features",
    productName: "Coffee Machine",
  },
  {
    id: 2,
    discount: undefined,
    image: [
      "/public/assets/coffemachine.jpg",
      "/public/assets/iphone.jpg",
      "/public/assets/microwave.jpg",
    ],
    make: "APPLE",
    starRating: 4.8,
    reviews: 498,
    price: 1130.0,
    oldPrice: undefined,
    description: "Latest iPhone with advanced features",
    productName: "iPhone 16 Pro 12GB",
    keyFeatures: [
      "6.7-inch Super Retina XDR display",
      "A17 Pro chip with 5-core GPU",
      "Pro camera system with 48MP main camera",
    ],
  },
  {
    id: 3,
    discount: undefined,
    image: [
      "/public/assets/coffemachine.jpg",
      "/public/assets/iphone.jpg",
      "/public/assets/microwave.jpg",
    ],
    make: "SMEG",
    starRating: 4.9,
    reviews: 948,
    price: 129.0,
    oldPrice: undefined,
    description: "High-quality microwave oven with multiple settings",
    productName: "Microwave oven",
    keyFeatures: [
      "900W power output",
      "10 power levels",
      "Auto-cook programs for convenience",
    ],
  },
  {
    id: 4,
    discount: "Sale 10%",
    image: [
      "/public/assets/coffemachine.jpg",
      "/public/assets//public/assets/iphone.jpg",
      "/public/assets//public/assets/microwave.jpg",
    ],
    make: "SMEG",
    starRating: 660,
    reviews: 6.0,
    price: 705.09,
    oldPrice: 900.0,
    description: "High-quality electric kettle with fast boiling",
    productName: "Electric kettle",
    keyFeatures: [
      "1.7L capacity",
      "Automatic shut-off for safety",
      "360-degree swivel base for easy pouring",
    ],
  },
  {
    id: 5,
    discount: "Sale 15%",
    image: [
      "/public/assets/coffemachine.jpg",
      "/public/assets/iphone.jpg",
      "/public/assets/microwave.jpg",
    ],
    make: "SMEG",
    starRating: 3.0,
    reviews: 340,
    price: 345.65,
    oldPrice: 500.0,
    description: "Compact hair dryer with multiple heat settings",
    productName: "Hair dryer",
    keyFeatures: [
      "Compact and lightweight design",
      "Multiple heat and speed settings",
      "Cool shot button for setting styles",
    ],
  },
  {
    id: 6,
    discount: undefined,
    image: [
      "/public/assets/coffemachine.jpg",
      "/public/assets/iphone.jpg",
      "/public/assets/microwave.jpg",
    ],
    make: "APPLE",
    starRating: 8.0,
    reviews: 8000,
    price: 300.0,
    oldPrice: undefined,
    description: "High-quality wireless headphones with noise cancellation",
    productName: "AirPods max",
    keyFeatures: [
      "Active Noise Cancellation and Transparency mode",
      "Spatial audio with dynamic head tracking",
      "Custom acoustic design for immersive sound",
    ],
  },
];
