export const productData = [
  {
    id: 1,
    discount: "Sale 15%",
    image: [
      "/assets/coffemachine-1.jpg",
      "/assets/coffemachine-2.jpg",
      "/assets/coffemachine-3.jpg",
      "/assets/coffemachine-4.jpg",
    ],
    make: "SMEG",
    starRating: 5.0,
    reviews: 5398,
    price: 985.99,
    oldPrice: 1056.0,
    description: "High-quality coffee machine with advanced features",
    productName: "Coffee Machine",
    category: "kitchen",
    isNewArrival: false,
  },
  {
    id: 2,
    discount: undefined,
    image: [
      "/assets/apple-phone.jpg",
      "/assets/coffemachine-2.jpg",
      "/assets/coffemachine-3.jpg",
      "/assets/coffemachine-4.jpg",
    ],
    make: "APPLE",
    starRating: 4.8,
    reviews: 498,
    price: 1130.0,
    oldPrice: undefined,
    description: "Latest iPhone with advanced features",
    productName: "iPhone 16 Pro 12GB",
    isNewArrival: false,
    keyFeatures: [
      "6.7-inch Super Retina XDR display",
      "A17 Pro chip with 5-core GPU",
      "Pro camera system with 48MP main camera",
    ],
    category: "smartphones",
  },
  {
    id: 3,
    discount: undefined,
    image: [
      "/assets/microwave.jpg",
      "/assets/coffemachine-2.jpg",
      "/assets/coffemachine-3.jpg",
      "/assets/coffemachine-4.jpg",
    ],
    make: "SMEG",
    starRating: 4.9,
    reviews: 948,
    price: 129.0,
    oldPrice: undefined,
    description: "High-quality microwave oven with multiple settings",
    productName: "Microwave oven",
    isNewArrival: false,
    keyFeatures: [
      "900W power output",
      "10 power levels",
      "Auto-cook programs for convenience",
    ],
    category: "Kitchen",
  },
  {
    id: 4,
    discount: "Sale 10%",
    image: [
      "/assets/ElectricKettle.jpg",
      "/assets/iphone.jpg",
      "/assets/microwave.jpg",
      "/assets/coffemachine-4.jpg",
    ],
    make: "SMEG",
    starRating: 660,
    reviews: 6.0,
    price: 705.09,
    oldPrice: 900.0,
    description: "High-quality electric kettle with fast boiling",
    productName: "Electric kettle",
    isNewArrival: false,
    keyFeatures: [
      "1.7L capacity",
      "Automatic shut-off for safety",
      "360-degree swivel base for easy pouring",
    ],
    category: "kitchen",
  },
  {
    id: 5,
    discount: "Sale 15%",
    image: [
      "/assets/Hairdryer.jpg",
      "/assets/iphone.jpg",
      "/assets/microwave.jpg",
      "/assets/coffemachine-4.jpg",
    ],
    make: "SMEG",
    starRating: 3.0,
    reviews: 340,
    price: 345.65,
    oldPrice: 500.0,
    description: "Compact hair dryer with multiple heat settings",
    productName: "Hair dryer",
    isNewArrival: false,
    keyFeatures: [
      "Compact and lightweight design",
      "Multiple heat and speed settingkls",
      "Cool shot button for setting styles",
    ],
    category: "kitchen",
  },
  {
    id: 6,
    discount: undefined,
    image: [
      "/assets/AirpodMax.jpg",
      "/assets/iphone.jpg",
      "/assets/microwave.jpg",
      "/assets/coffemachine-4.jpg",
    ],
    make: "APPLE",
    starRating: 8.0,
    reviews: 8000,
    price: 300.0,
    oldPrice: undefined,
    description: "High-quality wireless headphones with noise cancellation",
    productName: "AirPods max",
    isNewArrival: false,
    keyFeatures: [
      "Active Noise Cancellation and Transparency mode",
      "Spatial audio with dynamic head tracking",
      "Custom acoustic design for immersive sound",
    ],
    category: "smartphones",
  },
  {
    id: 7,
    discount: undefined,
    image: [
      "/assets/itel-phone.jpg",
      "/assets/iphone.jpg",
      "/assets/microwave.jpg",
      "/assets/coffemachine-4.jpg",
    ],
    make: "ITEL",
    starRating: 8.0,
    reviews: 8000,
    price: 150.0,
    oldPrice: undefined,
    description: "High-quality wireless headphones with noise cancellation",
    productName: "itel A70",
    isNewArrival: true,
    keyFeatures: [
      "Active Noise Cancellation and Transparency mode",
      "Spatial audio with dynamic head tracking",
      "Custom acoustic design for immersive sound",
    ],
    category: "smartphones",
  },
  {
    id: 8,
    discount: undefined,
    image: [
      "/assets/ps.png",
      "/assets/iphone.jpg",
      "/assets/microwave.jpg",
      "/assets/coffemachine-4.jpg",
    ],
    make: "APPLE",
    starRating: 8.0,
    reviews: 8000,
    price: 900.0,
    oldPrice: undefined,
    description: "High-quality wireless headphones with noise cancellation",
    productName: "PS5",
    isNewArrival: true,
    keyFeatures: [
      "Active Noise Cancellation and Transparency mode",
      "Spatial audio with dynamic head tracking",
      "Custom acoustic design for immersive sound",
    ],
    category: "smartphones",
  },
  {
    id: 9,
    discount: undefined,
    image: [
      "/assets/appleimac.jpg",
      "/assets/iphone.jpg",
      "/assets/microwave.jpg",
      "/assets/coffemachine-4.jpg",
    ],
    make: "APPLE",
    starRating: 8.0,
    reviews: 8000,
    price: 1500.0,
    oldPrice: undefined,
    description: "High-quality wireless headphones with noise cancellation",
    productName: "Apple iMac",
    isNewArrival: true,
    keyFeatures: [
      "Active Noise Cancellation and Transparency mode",
      "Spatial audio with dynamic head tracking",
      "Custom acoustic design for immersive sound",
    ],
    category: "gameconsole",
  },
];
